package by.epam.agency.command.constants;

public enum CommandType {
    SIGN_UP, SIGN_IN, HOME, REDIRECT, SIGN_OUT, GET_USERS_LIST, BLOCK_CLIENT,
    UNBLOCK_CLIENT, CREATE_ADMIN, UPDATE_ADMIN, UPDATE_CLIENT, DELETE_CLIENT,
}
